name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build for Linux and Windows
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Make build script executable
      run: chmod +x build.sh

    - name: Build both platforms
      run: ./build.sh

    - name: Extract assets
      run: |
        tar -xzf assets.tar.gz
        ls -la  # Debug: vérifier l'extraction

    - name: Package Linux
      run: |
        mkdir -p game/assets
        cp -r assets/* game/assets/
        cp out/linux/my_game game/
        tar czf mygame-linux.tar.gz game
        rm -rf game

    - name: Package Windows
      run: |
        mkdir -p game/assets
        cp -r assets/* game/assets/
        cp out/windows/my_game.exe game/
        tar czf mygame-windows.tar.gz game
        rm -rf game

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          mygame-linux.tar.gz
          mygame-windows.tar.gz
        body: |
          # 🎮 Cross-Platform SFML Game ${{ github.ref_name }}
          
          ## ✨ Features
          - ✅ **Linux & Windows** executables
          - ✅ **Docker-based** build system
          - ✅ **SFML built from source** with all dependencies
          - ✅ **Static linking** - no DLL dependencies required
          
          ## 📦 Downloads
          - **Linux**: `mygame-linux.tar.gz`
          - **Windows**: `mygame-windows.tar.gz`

          ## 🚀 How to Run
          - Extract the archive : `tar -xf  {archivename}`
          - Run `./game/my_game`
          
          ## 🎯 Game Features
          - [README.md](https://github.com/aautin/game_from_scratch/blob/.../README.md)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
